### ISSUE TITLE
Unable to check remaining uses without triggering an increment

### ISSUE THREAD

**Issue by jamesward1** [upstash/ratelimit#17]
For longer term rate limits, it's useful to show the end user a count of how many uses they have left within a rate limit window. Currently, there doesn't appear to be any way to access the key consistently without also triggering an increment on the number of uses. The key appears to be appended with a variable number value that gets in the way of doing a standard redis GET query.

Is there some way to consistently do a GET call on the key without implementing some further custom logic? If not, this would be nice to have.

**Comment by AtotheY** [comment]
+1 on this request - having a `limiter.checkLimit(key)`; would be really helpful - otherwise the only way for users to know how many requests they have left is to actually use a credit

**Comment by AtotheY** [comment]
Also wondering if there is a timeline for this - I know you mentioned it was backlog so just curious if it's coming anytime soon!

**Comment by chronark** [comment]
Damn, I didn't see your responses, sorry about that 
@AtotheY @jamesward1 
I'm working on some improvements and will ship this as well: tomorrow or next week.

**Comment by Than-DE** [comment]
Hi @chronark just wondering if this was still in the backlog. I am trying to look into how the increment events are being counted on redis but I can't seem to figure out how I would implement such a `checkLimit()` feature. 🙏

**Comment by Than-DE** [comment]
Ah not really, unfortunately @chronark. What I'd need is a way to check for a given `identifier` what is the remaining limit for the current window (fixed in my case). The same way `remaining` is returned by the `.limit()` method.

This is useful so that the user can see their remaining limit _without_ having to actually make another request. I am using this rate limiting for an expensive OpenAI API call and I'm only allowing X requests per day.

The [node-rate-limiter](https://github.com/jhurliman/node-rate-limiter) has a `getRemainingTokens()` method that does exactly what I need, but since I am using a serverless function, that package is not an option 😢

**Comment by chronark** [comment]
I see
the tricky thing is that it's different for each algorithm, which one are you using?

**Comment by Than-DE** [comment]
I am using the fixed window. I assume it is difficult because neither the identifier string entry nor the event hash in redis actually tells you _how many_ tokens were consumed _at what time_?

**Comment by chronark** [comment]
ah ok that one is fairly trivial

```ts
const intervalDuration = 1000 // 1s
const prefix = "@upstash/ratelimit"
const key = [prefix, identifier, Math.floor(Date.now() / intervalDuration)].join(":")

const remaining = await redis.get<number>(key)

```

**Comment by Than-DE** [comment]
Thanks, that is good to hear. I did try this but have a mismatch between what `.limit()` returns and what this calculation returns. Do you think it has something to do with the fact that I am testing this in the middle of an ongoing window and by tomorrow these two values will sync?

**Comment by chronark** [comment]
Ah sorry, yes you are correct.
It returns the used amount in the current window

**Comment by Than-DE** [comment]
Very cool, I think this would be nice to be documented. Shall I make a PR?

**Comment by chronark** [comment]
that'd be great, thanks

**Comment by Than-DE** [comment]
Revisiting this because I'm not 100% sure if this remaining token calculation for the fixed window really works. I checked the `.limit()` method and as far as I understand, it increments the redis key first before checking whether to set `success` to true: https://github.com/upstash/ratelimit/blob/c509628a6c1490121d810822ce7c880ddb02c44c/packages/sdk/src/single.ts#L158-L160



This means that when I call `.limit()` and check the returned `remaining` number it can also return a negative remaining value. For some reason, this doesn't happen every time, though.

![CleanShot 2023-06-19 at 19 39 55](https://github.com/upstash/ratelimit/assets/74593656/6f753201-cd26-45b9-a33a-c941cd6f4209)

**Comment by chronark** [comment]
yeah that looks like an oversight
it can return negative, but the check if it may pass also accounts for that
